import { prisma } from "@/lib/db";
import { requireWriteAccess, SessionError } from "@/lib/session";
import { toTermFee } from "@/lib/term-fee-mapper";
import { writeAuditLog } from "@/lib/audit";
import type { TermFee } from "@/lib/mock";

export const runtime = "nodejs";

const INCLUDE = { projectTermInstitution: { include: { projectTerm: { include: { project: true } }, institution: true } } } as const;
const MOCK_TO_DB_STATUS: Record<string, string> = { SCHEDULED: "DRAFT", DRAFT: "DRAFT", CONFIRMED: "CONFIRMED", BILLED: "BILLED" };

type Params = { params: Promise<{ id: string }> };
type Extra = Record<string, unknown>;

export async function PATCH(request: Request, { params }: Params) {
  const { id } = await params;
  let actor;
  try {
    actor = await requireWriteAccess(["fees", "fees-sales", "fees-info-edit"]);
  } catch (err) {
    if (err instanceof SessionError) return Response.json({ ok: false, error: err.message }, { status: err.status });
    throw err;
  }

  let body: Partial<TermFee>;
  try {
    body = await request.json();
  } catch {
    return Response.json({ ok: false, error: "잘못된 요청입니다." }, { status: 400 });
  }

  const before = await prisma.termFee.findUnique({ where: { id }, include: INCLUDE });
  if (!before) return Response.json({ ok: false, error: "연차수수료를 찾을 수 없습니다." }, { status: 404 });

  const prevExtra: Extra = before.extraData ? JSON.parse(before.extraData) : {};
  const extraKeys = [
    "feeRate", "calculatedFee", "isAutoGenerated", "unclaimedFee", "manualOverride", "otherFirmHandled",
    "auditFirm", "docRequestDate", "docReplyDate", "termStartDate", "termEndDate", "billingType", "institutionType",
  ] as const;
  const nextExtra = { ...prevExtra };
  for (const key of extraKeys) {
    if (key in body) nextExtra[key] = (body as Record<string, unknown>)[key];
  }

  const updated = await prisma.$transaction(async (tx) => {
    const row = await tx.termFee.update({
      where: { id },
      data: {
        projectBudget: body.budget !== undefined ? BigInt(Math.round(body.budget)) : undefined,
        standardFee: body.standardFee !== undefined ? BigInt(Math.round(body.standardFee)) : undefined,
        appliedFee: body.appliedFee !== undefined ? BigInt(Math.round(body.appliedFee)) : undefined,
        billedFee: body.status === "BILLED" && body.appliedFee !== undefined ? BigInt(Math.round(body.appliedFee)) : undefined,
        status: body.status !== undefined ? MOCK_TO_DB_STATUS[body.status] ?? undefined : undefined,
        notes: body.manualOverrideReason !== undefined ? body.manualOverrideReason ?? null : undefined,
        extraData: JSON.stringify(nextExtra),
      },
      include: INCLUDE,
    });
    const afterFee = toTermFee(row);
    await writeAuditLog(tx, {
      actorUserId: actor.userId,
      entityType: "termFee",
      entityId: row.id,
      entityLabel: `${afterFee.projectNumber} · ${afterFee.institutionName}`,
      action: "UPDATE",
      before: toTermFee(before) as unknown as Record<string, unknown>,
      after: afterFee as unknown as Record<string, unknown>,
    });
    return row;
  });

  return Response.json({ ok: true, termFee: toTermFee(updated) });
}
