import { prisma } from "@/lib/db";
import { requireWriteAccess, SessionError } from "@/lib/session";
import { getOrCreatePti } from "@/lib/pti-helper";
import type { TermFee, TermFeeCalc } from "@/lib/mock";

export const runtime = "nodejs";

type Params = { params: Promise<{ id: string }> };

const MOCK_TO_DB_TERM_FEE_STATUS: Record<string, string> = { SCHEDULED: "DRAFT", DRAFT: "DRAFT", CONFIRMED: "CONFIRMED", BILLED: "BILLED" };

// autoGenerateTermFees(lib/store.ts)가 클라이언트에서 계산을 끝낸 뒤, 그 결과(해당 프로젝트분
// termFees+termFeeCalcs 전체)를 통째로 넘겨받아 DB에 반영한다. 계산 로직 자체는 여기 없다 —
// 이미 계산이 끝난 최종 상태를 그대로 반영(upsert + 빠진 것 정리)만 한다.
export async function POST(request: Request, { params }: Params) {
  const { id: projectId } = await params;
  let actor;
  try {
    actor = await requireWriteAccess(["fees", "projects"]);
  } catch (err) {
    if (err instanceof SessionError) return Response.json({ ok: false, error: err.message }, { status: err.status });
    throw err;
  }

  let body: { termFees: TermFee[]; termFeeCalcs: TermFeeCalc[] };
  try {
    body = await request.json();
  } catch {
    return Response.json({ ok: false, error: "잘못된 요청입니다." }, { status: 400 });
  }

  const project = await prisma.project.findUnique({ where: { id: projectId } });
  if (!project) return Response.json({ ok: false, error: "과제를 찾을 수 없습니다." }, { status: 404 });

  const feePolicy =
    (project.fundingAgencyId && (await prisma.feePolicy.findFirst({ where: { fundingAgencyId: project.fundingAgencyId } }))) ??
    (await prisma.feePolicy.findFirst());
  if (!feePolicy) return Response.json({ ok: false, error: "적용 가능한 수수료 정책이 없습니다." }, { status: 400 });

  await prisma.$transaction(async (tx) => {
    // term_fee_calcs: 이 과제분 전체를 교체
    await tx.termFeeCalc.deleteMany({ where: { projectId } });
    for (const tfc of body.termFeeCalcs) {
      await tx.termFeeCalc.create({
        data: {
          projectId,
          projectNumber: tfc.projectNumber,
          projectName: tfc.projectName,
          fundingAgencyId: project.fundingAgencyId ?? tfc.agencyId,
          termYear: tfc.termYear,
          termNumber: tfc.termNumber,
          stageNumber: tfc.stageNumber,
          workType: tfc.workType,
          totalCashBudget: BigInt(Math.round(tfc.totalCashBudget)),
          coInstCount: tfc.coInstCount,
          baseFee: BigInt(Math.round(tfc.baseFee)),
          addonFee: BigInt(Math.round(tfc.addonFee)),
          standardFee: BigInt(Math.round(tfc.standardFee)),
          nonExemptCashBudget: BigInt(Math.round(tfc.nonExemptCashBudget)),
          nonExemptCoInstCount: tfc.nonExemptCoInstCount,
          nonExemptBaseFee: BigInt(Math.round(tfc.nonExemptBaseFee)),
          nonExemptAddonFee: BigInt(Math.round(tfc.nonExemptAddonFee)),
          generalFee: BigInt(Math.round(tfc.generalFee)),
          exemptFeeTotal: BigInt(Math.round(tfc.exemptFeeTotal)),
          exemptBreakdown: JSON.stringify(tfc.exemptBreakdown ?? []),
          calculatedFee: BigInt(Math.round(tfc.calculatedFee)),
          generalCalcFee: BigInt(Math.round(tfc.generalCalcFee)),
          generalBillingFee: BigInt(Math.round(tfc.generalBillingFee)),
          generalUnclaimedFee: BigInt(Math.round(tfc.generalUnclaimedFee)),
          carriedOverUnclaimed: BigInt(Math.round(tfc.carriedOverUnclaimed)),
          totalBillingFee: BigInt(Math.round(tfc.totalBillingFee)),
          overrides: JSON.stringify(tfc.overrides ?? []),
          status: tfc.status,
        },
      });
    }

    // term_fees: (institutionId, termNumber) 기준으로 PTI를 찾거나 만들어 upsert
    const touchedPtiIds = new Set<string>();
    for (const t of body.termFees) {
      const ptiId = await getOrCreatePti(tx, projectId, t.termNumber, t.institutionId, "PARTICIPATING", BigInt(Math.round(t.budget)));
      touchedPtiIds.add(ptiId);
      const data = {
        feePolicyId: feePolicy.id,
        projectBudget: BigInt(Math.round(t.budget)),
        standardFee: BigInt(Math.round(t.standardFee ?? t.calculatedFee)),
        appliedFee: BigInt(Math.round(t.appliedFee)),
        billedFee: t.status === "BILLED" ? BigInt(Math.round(t.appliedFee)) : null,
        status: MOCK_TO_DB_TERM_FEE_STATUS[t.status] ?? "DRAFT",
        notes: t.manualOverrideReason ?? null,
        extraData: JSON.stringify({
          feeRate: t.feeRate, calculatedFee: t.calculatedFee, isAutoGenerated: t.isAutoGenerated,
          unclaimedFee: t.unclaimedFee, manualOverride: t.manualOverride, otherFirmHandled: t.otherFirmHandled,
          auditFirm: t.auditFirm, docRequestDate: t.docRequestDate, docReplyDate: t.docReplyDate,
          termStartDate: t.termStartDate, termEndDate: t.termEndDate, billingType: t.billingType,
          institutionType: t.institutionType,
        }),
      };
      await tx.termFee.upsert({
        where: { projectTermInstitutionId: ptiId },
        create: { projectTermInstitutionId: ptiId, ...data },
        update: data,
      });
    }

    // 이 과제 소속 PTI 중 이번에 안 온 것들의 기존 term_fee는 엔진이 더 이상 유효하지 않다고
    // 판단한 것이므로 정리한다 (PTI 자체는 다른 도메인이 참조할 수 있어 지우지 않는다).
    const terms = await tx.projectTerm.findMany({ where: { projectId }, select: { id: true } });
    const allPtis = await tx.projectTermInstitution.findMany({
      where: { projectTermId: { in: terms.map((t) => t.id) } },
      select: { id: true },
    });
    const orphanIds = allPtis.map((p) => p.id).filter((ptiId) => !touchedPtiIds.has(ptiId));
    if (orphanIds.length > 0) {
      await tx.termFee.deleteMany({ where: { projectTermInstitutionId: { in: orphanIds } } });
    }
  });

  await prisma.auditLog.create({
    data: {
      userId: actor.userId,
      action: "UPDATE",
      resourceType: "termFeeSync",
      resourceId: projectId,
      newValues: JSON.stringify({ termFeeCount: body.termFees.length, termFeeCalcCount: body.termFeeCalcs.length }),
    },
  });

  return Response.json({ ok: true });
}
