import { prisma } from "@/lib/db";
import { requireWriteAccess, SessionError } from "@/lib/session";
import { toTermFee } from "@/lib/term-fee-mapper";
import { getOrCreatePti } from "@/lib/pti-helper";
import type { TermFee } from "@/lib/mock";

export const runtime = "nodejs";

const INCLUDE = { projectTermInstitution: { include: { projectTerm: { include: { project: true } }, institution: true } } } as const;

const MOCK_TO_DB_STATUS: Record<string, string> = { SCHEDULED: "DRAFT", DRAFT: "DRAFT", CONFIRMED: "CONFIRMED", BILLED: "BILLED" };

export async function GET() {
  const rows = await prisma.termFee.findMany({ include: INCLUDE });
  return Response.json({ ok: true, termFees: rows.map(toTermFee) });
}

export async function POST(request: Request) {
  try {
    await requireWriteAccess(["fees", "fees-sales", "fees-info-edit"]);
  } catch (err) {
    if (err instanceof SessionError) return Response.json({ ok: false, error: err.message }, { status: err.status });
    throw err;
  }

  let body: Omit<TermFee, "id">;
  try {
    body = await request.json();
  } catch {
    return Response.json({ ok: false, error: "잘못된 요청입니다." }, { status: 400 });
  }
  if (!body.projectNumber || !body.institutionId) {
    return Response.json({ ok: false, error: "과제번호, 참여기관은 필수입니다." }, { status: 400 });
  }

  const project = await prisma.project.findUnique({ where: { projectNumber: body.projectNumber } });
  if (!project) return Response.json({ ok: false, error: "과제를 찾을 수 없습니다." }, { status: 404 });
  const feePolicy = await prisma.feePolicy.findFirst({ where: { fundingAgencyId: project.fundingAgencyId ?? undefined } })
    ?? await prisma.feePolicy.findFirst();
  if (!feePolicy) return Response.json({ ok: false, error: "적용 가능한 수수료 정책이 없습니다." }, { status: 400 });

  const ptiId = await getOrCreatePti(prisma, project.id, body.termNumber, body.institutionId, "PARTICIPATING", BigInt(Math.round(body.budget)));

  const created = await prisma.termFee.create({
    data: {
      projectTermInstitutionId: ptiId,
      feePolicyId: feePolicy.id,
      projectBudget: BigInt(Math.round(body.budget)),
      standardFee: BigInt(Math.round(body.standardFee ?? body.calculatedFee)),
      appliedFee: BigInt(Math.round(body.appliedFee)),
      billedFee: body.status === "BILLED" ? BigInt(Math.round(body.appliedFee)) : null,
      status: MOCK_TO_DB_STATUS[body.status] ?? "DRAFT",
      notes: body.manualOverrideReason ?? null,
      extraData: JSON.stringify({
        feeRate: body.feeRate, calculatedFee: body.calculatedFee, isAutoGenerated: body.isAutoGenerated,
        unclaimedFee: body.unclaimedFee, manualOverride: body.manualOverride, otherFirmHandled: body.otherFirmHandled,
        auditFirm: body.auditFirm, docRequestDate: body.docRequestDate, docReplyDate: body.docReplyDate,
        termStartDate: body.termStartDate, termEndDate: body.termEndDate, billingType: body.billingType,
        institutionType: body.institutionType,
      }),
    },
    include: INCLUDE,
  });

  // 변경이력은 클라이언트 record()가 /api/audit-log로 남긴다(중복 방지).
  return Response.json({ ok: true, termFee: toTermFee(created) });
}
