import type { TermFee as PrismaTermFee, ProjectTermInstitution, ProjectTerm, Project as PrismaProject, Institution as PrismaInstitution } from "@prisma/client";
import type { TermFee } from "./mock";

// project/institution은 실제로 쓰는 필드(아래 toTermFee 참고)만 좁혀서 select한다 — project의
// extraData(NVarChar(Max), 연차별 이력이 쌓인 JSON)까지 매 행마다 통째로 끌고 오면 연차수수료가
// 쌓일수록 이 API가 느려진다.
export type TermFeeWithRelations = PrismaTermFee & {
  projectTermInstitution: ProjectTermInstitution & {
    projectTerm: ProjectTerm & { project: Pick<PrismaProject, "projectNumber" | "projectName"> };
    institution: Pick<PrismaInstitution, "institutionName" | "institutionType">;
  };
};

type Extra = {
  feeRate?: number;
  calculatedFee?: number;
  isAutoGenerated?: boolean;
  unclaimedFee?: number;
  manualOverride?: boolean;
  otherFirmHandled?: boolean;
  auditFirm?: string;
  docRequestDate?: string;
  docReplyDate?: string;
  termStartDate?: string;
  termEndDate?: string;
  billingType?: TermFee["billingType"];
  institutionType?: string;
};

const DB_TO_MOCK_STATUS: Record<string, TermFee["status"]> = {
  DRAFT: "DRAFT", CONFIRMED: "CONFIRMED", BILLED: "BILLED",
};

export function toTermFee(t: TermFeeWithRelations): TermFee {
  const extra: Extra = t.extraData ? JSON.parse(t.extraData) : {};
  const pti = t.projectTermInstitution;
  return {
    id: t.id,
    projectNumber: pti.projectTerm.project.projectNumber,
    projectName: pti.projectTerm.project.projectName,
    termYear: pti.projectTerm.termYear,
    termNumber: pti.projectTerm.termNumber,
    institutionId: pti.institutionId,
    institutionName: pti.institution.institutionName,
    institutionType: extra.institutionType ?? pti.institution.institutionType ?? "",
    budget: Number(t.projectBudget),
    feeRate: extra.feeRate ?? 0,
    calculatedFee: extra.calculatedFee ?? Number(t.standardFee),
    appliedFee: Number(t.appliedFee ?? 0),
    status: DB_TO_MOCK_STATUS[t.status] ?? "DRAFT",
    isAutoGenerated: extra.isAutoGenerated,
    standardFee: Number(t.standardFee),
    unclaimedFee: extra.unclaimedFee,
    manualOverride: extra.manualOverride,
    manualOverrideReason: t.notes ?? undefined,
    otherFirmHandled: extra.otherFirmHandled,
    auditFirm: extra.auditFirm,
    docRequestDate: extra.docRequestDate,
    docReplyDate: extra.docReplyDate,
    termStartDate: extra.termStartDate,
    termEndDate: extra.termEndDate,
    billingType: extra.billingType,
  };
}
